function Save-FGCorrelationRuleset {
    <#
    .SYNOPSIS
        Saves an account correlation ruleset to Azure SQL.

    .DESCRIPTION
        Persists a correlation ruleset (generated by New-FGCorrelationRuleset or custom) to the
        GraphCorrelationRulesets temporal table. Uses MERGE for upsert semantics — existing
        rulesets are updated, new ones are inserted.

    .PARAMETER Ruleset
        The ruleset object (from New-FGCorrelationRuleset or custom).

    .PARAMETER Id
        Optional identifier for the ruleset. Defaults to "default".

    .PARAMETER ConfigFile
        Optional path to FortigiGraph config file for SQL connection.

    .EXAMPLE
        $ruleset = New-FGCorrelationRuleset
        Save-FGCorrelationRuleset -Ruleset $ruleset

    .EXAMPLE
        Save-FGCorrelationRuleset -Ruleset $ruleset -Id "contoso-custom" -ConfigFile .\Config\mycompany.json
    #>
    [alias("Save-CorrelationRuleset")]
    [cmdletbinding()]
    Param(
        [Parameter(Mandatory = $true)]
        [object]$Ruleset,

        [Parameter(Mandatory = $false)]
        [string]$Id = "default",

        [Parameter(Mandatory = $false)]
        [string]$ConfigFile
    )

    Write-Host "--- Saving Correlation Ruleset to SQL ---" -ForegroundColor Cyan

    # Ensure SQL connection
    if (-not $global:FGSQLConnectionString) {
        if ($ConfigFile) {
            Connect-FGSQLServer -ConfigFile $ConfigFile
        } else {
            throw "Not connected to SQL Server. Run Connect-FGSQLServer first or provide -ConfigFile."
        }
    }

    # Ensure table exists
    $tableExists = Invoke-FGSQLCommand -ScriptBlock {
        param($connection)
        $cmd = $connection.CreateCommand()
        $cmd.CommandText = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'GraphCorrelationRulesets' AND TABLE_SCHEMA = 'dbo'"
        return [int]$cmd.ExecuteScalar() -gt 0
    }

    if (-not $tableExists) {
        Write-Host "  Creating GraphCorrelationRulesets table..." -ForegroundColor Gray
        $columns = [ordered]@{
            'id'          = 'NVARCHAR(200) NOT NULL'
            'version'     = 'NVARCHAR(20) NULL'
            'generatedAt' = 'DATETIME2 NULL'
            'rulesetJson' = 'NVARCHAR(MAX) NOT NULL'
        }
        Initialize-FGSQLTable -TableName 'GraphCorrelationRulesets' -Columns $columns -PrimaryKey 'id'
    }

    # Serialize ruleset to JSON
    $rulesetJson = $Ruleset | ConvertTo-Json -Depth 100 -Compress
    $version = if ($Ruleset.version) { $Ruleset.version } else { [DBNull]::Value }
    $generatedAt = if ($Ruleset.generated_at) { [DateTime]::Parse($Ruleset.generated_at) } else { [DateTime]::UtcNow }

    # MERGE upsert
    Invoke-FGSQLCommand -ScriptBlock {
        param($connection)
        $cmd = $connection.CreateCommand()
        $cmd.CommandTimeout = 60
        $cmd.CommandText = @"
MERGE dbo.GraphCorrelationRulesets AS target
USING (SELECT @id AS id) AS source ON target.id = source.id
WHEN MATCHED THEN UPDATE SET
    version = @version,
    generatedAt = @generatedAt,
    rulesetJson = @rulesetJson
WHEN NOT MATCHED THEN INSERT (id, version, generatedAt, rulesetJson)
VALUES (@id, @version, @generatedAt, @rulesetJson);
"@
        $cmd.Parameters.AddWithValue("@id", $Id) | Out-Null
        $cmd.Parameters.AddWithValue("@version", $version) | Out-Null
        $cmd.Parameters.AddWithValue("@generatedAt", $generatedAt) | Out-Null
        $cmd.Parameters.AddWithValue("@rulesetJson", $rulesetJson) | Out-Null
        $cmd.ExecuteNonQuery() | Out-Null
    }

    $sizeKB = [Math]::Round($rulesetJson.Length / 1KB, 1)
    Write-Host "  Correlation ruleset saved: id='$Id' (version=$version, $sizeKB KB)" -ForegroundColor Green
}
